name: 🐞 Bug Report
description: Tell us about something that's not working as expected.
labels: [bug]

body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: How can we see what you're seeing? Specific is terrific.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened? Include screenshots if applicable.
    validations:
      required: true

  - type: input
    id: browser
    attributes:
      label: Browser
      description: Browser name and version
      placeholder: "Firefox 146.0.1"
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: HTE version
      description: Extension version (visible in footer on the right side)
      placeholder: "0.1.0"
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false
