name: ✨ Feature Request
description: Suggest a new feature or enhancement
labels: [enhancement]

body:
  - type: textarea
    id: what
    attributes:
      label: What feature would you like to see and why is it useful?
      description: A clear and concise description of what you want to see. What problem does it solve?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
